# Generated by Cloud66 Starter
FROM ruby:2.5.3

RUN printf "deb http://deb.debian.org/debian buster main contrib non-free\ndeb-src http://deb.debian.org/debian buster main contrib non-free\ndeb http://deb.debian.org/debian-security/ buster/updates main contrib non-free\ndeb-src http://deb.debian.org/debian-security/ buster/updates main contrib non-free\ndeb http://deb.debian.org/debian buster-updates main contrib non-free\ndeb-src http://deb.debian.org/debian buster-updates main contrib non-free\n" > /etc/apt/sources.list
RUN apt-get --allow-unauthenticated --allow-insecure-repositories update -qq
RUN apt-get install -y --allow-unauthenticated build-essential

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN gem install bundler -v 2.3.26
RUN bundle install

ADD . $APP_HOME

RUN apt-get update --allow-unauthenticated --allow-insecure-repositories -qq && apt-get install -y --allow-unauthenticated apt-transport-https ca-certificates
RUN ./install_node.sh
RUN apt-get update --allow-unauthenticated --allow-insecure-repositories -qq && apt-get install -y --allow-unauthenticated nodejs
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update --allow-unauthenticated --allow-insecure-repositories -qq && apt-get install -y --allow-unauthenticated yarn

RUN yarn install --check-files
RUN bundle exec rails assets:precompile
